import { useState } from 'react';
import ReactMarkdown from 'react-markdown';
import rehypeSanitize from 'rehype-sanitize';
import { jsPDF } from 'jspdf';
import './Stage3.css';

export default function Stage3({ finalResponse, originalQuestion, messageId, onRespond, isLoading }) {
  const [copied, setCopied] = useState(false);

  // Safety check for invalid data
  if (!finalResponse || typeof finalResponse !== 'object') {
    return null;
  }

  const handleCopy = async () => {
    const formatted = `QUESTION:\n${originalQuestion || 'N/A'}\n\nDECISION:\n${finalResponse.response || 'No response'}`;
    try {
      await navigator.clipboard.writeText(formatted);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error('Failed to copy:', err);
    }
  };

  const handleDownloadPDF = () => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 20;
    const maxWidth = pageWidth - margin * 2;
    let yPos = 20;

    // Title
    doc.setFontSize(18);
    doc.setFont('helvetica', 'bold');
    doc.text('DecidePlease Decision', margin, yPos);
    yPos += 10;

    // Date
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(100);
    doc.text(`Generated: ${new Date().toLocaleDateString()} at ${new Date().toLocaleTimeString()}`, margin, yPos);
    yPos += 15;

    // Question section
    doc.setTextColor(0);
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text('Question:', margin, yPos);
    yPos += 7;

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(11);
    const questionLines = doc.splitTextToSize(originalQuestion || 'N/A', maxWidth);
    doc.text(questionLines, margin, yPos);
    yPos += questionLines.length * 6 + 10;

    // Decision section
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text('Decision:', margin, yPos);
    yPos += 7;

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(11);
    const decisionText = finalResponse.response || 'No response';
    const decisionLines = doc.splitTextToSize(decisionText, maxWidth);

    // Handle multi-page content
    for (let i = 0; i < decisionLines.length; i++) {
      if (yPos > 270) {
        doc.addPage();
        yPos = 20;
      }
      doc.text(decisionLines[i], margin, yPos);
      yPos += 6;
    }

    // Footer
    const pageCount = doc.internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(8);
      doc.setTextColor(150);
      doc.text('Generated by DecidePlease', margin, 285);
      doc.text(`Page ${i} of ${pageCount}`, pageWidth - margin - 20, 285);
    }

    doc.save('decision.pdf');
  };

  const handleRespond = () => {
    if (onRespond && messageId) {
      onRespond(messageId);
    }
  };

  return (
    <div className="stage stage3">
      <h3 className="stage-title">Final Decision</h3>
      <div className="final-response">
        <div className="final-text markdown-content">
          <ReactMarkdown rehypePlugins={[rehypeSanitize]}>{finalResponse.response || 'No response available'}</ReactMarkdown>
        </div>

        {!isLoading && (
          <div className="stage3-actions">
            <button
              className="action-btn respond-btn"
              onClick={handleRespond}
              title="Add information or ask a follow-up about this decision"
            >
              Respond
            </button>
            <button
              className="action-btn copy-btn"
              onClick={handleCopy}
              title="Copy decision to clipboard"
            >
              {copied ? 'Copied!' : 'Copy'}
            </button>
            <button
              className="action-btn pdf-btn"
              onClick={handleDownloadPDF}
              title="Download as PDF"
            >
              PDF
            </button>
          </div>
        )}
      </div>
    </div>
  );
}
