import UnifiedHeader from './UnifiedHeader';
import UnifiedFooter from './UnifiedFooter';
import './LegalPages.css';

export default function TermsPage() {
  return (
    <div className="legal-page">
      <UnifiedHeader />
      <main className="legal-content">
        <div className="legal-container">
          <h1>Terms of Service</h1>
          <p className="legal-updated">Last updated: January 2025</p>

          <section>
            <h2>1. Acceptance of Terms</h2>
            <p>
              By accessing or using DecidePlease ("the Service"), you agree to be bound
              by these Terms of Service. If you do not agree to these terms, please do
              not use the Service.
            </p>
          </section>

          <section>
            <h2>2. Description of Service</h2>
            <p>
              DecidePlease is an AI-powered decision-making assistant that:
            </p>
            <ul>
              <li>Collects responses from multiple AI models to your questions</li>
              <li>Conducts anonymous peer review among the AI models</li>
              <li>Synthesizes a final recommendation based on the deliberation</li>
            </ul>
            <p>
              The Service is provided for informational and educational purposes only.
              AI-generated recommendations should not be considered professional advice.
            </p>
          </section>

          <section>
            <h2>3. User Accounts</h2>
            <p>
              To use the Service, you must create an account with a valid email address
              and password. You are responsible for:
            </p>
            <ul>
              <li>Maintaining the confidentiality of your account credentials</li>
              <li>All activities that occur under your account</li>
              <li>Notifying us immediately of any unauthorized use</li>
            </ul>
          </section>

          <section>
            <h2>4. Credits and Payments</h2>

            <h3>Credit System</h3>
            <p>
              The Service operates on a credit-based system. New accounts receive
              complimentary credits. Additional credits can be purchased through our
              payment system.
            </p>

            <h3>Credit Usage</h3>
            <ul>
              <li><strong>Quick mode:</strong> 1 credit per query</li>
              <li><strong>Standard mode:</strong> 2 credits per query</li>
              <li><strong>Extra Care mode:</strong> 3 credits per query</li>
            </ul>

            <h3>Refund Policy</h3>
            <p>
              Credit purchases are generally non-refundable. However, we may provide
              refunds at our discretion for:
            </p>
            <ul>
              <li>Technical failures that prevented service delivery</li>
              <li>Duplicate charges</li>
              <li>Unauthorized transactions</li>
            </ul>
            <p>
              To request a refund, contact us at support@decideplease.com within 30 days
              of purchase.
            </p>
          </section>

          <section>
            <h2>5. Acceptable Use</h2>
            <p>You agree not to use the Service to:</p>
            <ul>
              <li>Violate any applicable laws or regulations</li>
              <li>Submit illegal, harmful, or offensive content</li>
              <li>Attempt to manipulate or abuse the AI systems</li>
              <li>Circumvent rate limits or security measures</li>
              <li>Resell or redistribute the Service without permission</li>
              <li>Collect data about other users</li>
              <li>Interfere with or disrupt the Service</li>
            </ul>
          </section>

          <section>
            <h2>6. Intellectual Property</h2>

            <h3>Our Content</h3>
            <p>
              The Service, including its design, features, and underlying technology,
              is owned by DecidePlease. You may not copy, modify, or distribute our
              proprietary content without permission.
            </p>

            <h3>Your Content</h3>
            <p>
              You retain ownership of the questions you submit. By using the Service,
              you grant us a limited license to process your queries through AI systems
              and store the results for your access.
            </p>

            <h3>AI-Generated Content</h3>
            <p>
              Responses generated by the AI models are provided for your personal use.
              You may use these responses for your decision-making purposes.
            </p>
          </section>

          <section>
            <h2>7. Disclaimer of Warranties</h2>
            <p>
              THE SERVICE IS PROVIDED "AS IS" WITHOUT WARRANTIES OF ANY KIND. WE DO NOT
              GUARANTEE THAT:
            </p>
            <ul>
              <li>The Service will be uninterrupted or error-free</li>
              <li>AI recommendations will be accurate or suitable for your needs</li>
              <li>Results will meet your expectations</li>
            </ul>
            <p>
              <strong>AI recommendations are not professional advice.</strong> For important
              decisions involving legal, medical, financial, or other professional matters,
              consult qualified professionals.
            </p>
          </section>

          <section>
            <h2>8. Limitation of Liability</h2>
            <p>
              TO THE MAXIMUM EXTENT PERMITTED BY LAW, DECIDEPLEASE SHALL NOT BE LIABLE FOR:
            </p>
            <ul>
              <li>Any indirect, incidental, special, or consequential damages</li>
              <li>Decisions made based on AI recommendations</li>
              <li>Loss of profits, data, or business opportunities</li>
              <li>Service interruptions or technical failures</li>
            </ul>
            <p>
              Our total liability shall not exceed the amount you paid for credits in
              the 12 months preceding the claim.
            </p>
          </section>

          <section>
            <h2>9. Indemnification</h2>
            <p>
              You agree to indemnify and hold harmless DecidePlease and its officers,
              directors, employees, and agents from any claims, damages, or expenses
              arising from your use of the Service or violation of these Terms.
            </p>
          </section>

          <section>
            <h2>10. Modifications to Service</h2>
            <p>
              We reserve the right to modify, suspend, or discontinue the Service at
              any time. We will provide reasonable notice for significant changes when
              possible.
            </p>
          </section>

          <section>
            <h2>11. Termination</h2>
            <p>
              We may terminate or suspend your account for violations of these Terms.
              You may close your account at any time. Upon termination, unused credits
              are generally non-refundable.
            </p>
          </section>

          <section>
            <h2>12. Governing Law</h2>
            <p>
              These Terms shall be governed by and construed in accordance with the laws
              of the United States, without regard to conflict of law principles.
            </p>
          </section>

          <section>
            <h2>13. Changes to Terms</h2>
            <p>
              We may update these Terms from time to time. We will notify you of material
              changes by email or by posting a notice on our website. Continued use of
              the Service after changes constitutes acceptance of the new Terms.
            </p>
          </section>

          <section>
            <h2>14. Contact Information</h2>
            <p>
              For questions about these Terms, please contact us at:
            </p>
            <p className="contact-info">
              <strong>Email:</strong> legal@decideplease.com
            </p>
          </section>
        </div>
      </main>
      <UnifiedFooter />
    </div>
  );
}
