import DossierHeader from './DossierHeader';
import DossierBody from './DossierBody';
import DossierFooter from './DossierFooter';
import './VerdictDossier.css';

/**
 * Verdict Dossier - The legal briefing-style output document.
 * Contains header, body (markdown), and footer (voting record).
 */
export default function VerdictDossier({
  question,
  stage1,
  stage3,
  metadata = {},
  isLoading = false,
  isPrevious = false, // Stacked behind current dossier
}) {
  const {
    aggregate_rankings: aggregateRankings,
    stage2Skipped,
    mode,
  } = metadata;

  // Get chairman model from stage3 or metadata
  const chairmanModel = stage3?.model || 'google/gemini-3-pro-preview';
  const modelCount = stage1?.length || 5;
  const stage3Content = stage3?.response || '';

  return (
    <div className={`verdict-dossier ${isLoading ? 'loading' : ''} ${isPrevious ? 'previous' : 'current'}`}>
      <DossierHeader
        question={question}
        chairmanModel={chairmanModel}
        modelCount={modelCount}
        aggregateRankings={aggregateRankings}
      />

      <DossierBody
        content={stage3Content}
        isLoading={isLoading && !stage3Content}
      />

      <DossierFooter
        aggregateRankings={aggregateRankings}
        stage2Skipped={stage2Skipped || mode === 'quick'}
      />

      {/* Actions (Copy, PDF) - positioned at bottom right */}
      {stage3Content && !isLoading && (
        <div className="dossier-actions">
          <button
            className="action-btn"
            onClick={() => handleCopy(question, stage3Content)}
            title="Copy to clipboard"
          >
            <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
              <rect x="9" y="9" width="13" height="13" rx="2" ry="2" />
              <path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1" />
            </svg>
            Copy
          </button>

          <button
            className="action-btn"
            onClick={() => handlePDF(question, stage3Content)}
            title="Download as PDF"
          >
            <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
              <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z" />
              <polyline points="14 2 14 8 20 8" />
              <line x1="12" y1="18" x2="12" y2="12" />
              <line x1="9" y1="15" x2="15" y2="15" />
            </svg>
            PDF
          </button>
        </div>
      )}
    </div>
  );
}

// Copy handler
function handleCopy(question, content) {
  const text = `QUESTION:\n${question}\n\nDECISION:\n${content}`;
  navigator.clipboard.writeText(text).then(() => {
    // Could show a toast notification here
    console.log('Copied to clipboard');
  });
}

// PDF handler (basic implementation)
async function handlePDF(question, content) {
  try {
    // Dynamic import jsPDF
    const { default: jsPDF } = await import('jspdf');
    const doc = new jsPDF();

    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 20;
    const maxWidth = pageWidth - margin * 2;
    let y = margin;

    // Title
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('COUNCIL VERDICT', margin, y);
    y += 10;

    // Question
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(100);
    doc.text('QUERY:', margin, y);
    y += 6;

    doc.setTextColor(0);
    const questionLines = doc.splitTextToSize(question, maxWidth);
    doc.text(questionLines, margin, y);
    y += questionLines.length * 5 + 10;

    // Divider
    doc.setDrawColor(200);
    doc.line(margin, y, pageWidth - margin, y);
    y += 10;

    // Decision
    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text('DECISION:', margin, y);
    y += 6;

    doc.setTextColor(0);
    const contentLines = doc.splitTextToSize(content, maxWidth);

    // Handle pagination
    const pageHeight = doc.internal.pageSize.getHeight();
    for (const line of contentLines) {
      if (y > pageHeight - margin) {
        doc.addPage();
        y = margin;
      }
      doc.text(line, margin, y);
      y += 5;
    }

    // Footer
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text('Generated by DecidePlease', margin, pageHeight - 10);

    // Save
    const filename = `decision-${Date.now()}.pdf`;
    doc.save(filename);
  } catch (error) {
    console.error('Failed to generate PDF:', error);
  }
}
